### PR TITLE
#111: Create ErrorHandling implementation that throws an exception on error detected

### LINKED ISSUE #111: Create ErrorHandling implementation that throws an exception on error detected
## Background
One of the provided `ErrorHandling` implementations. The `ErrorMessage` entries should immediately thrown as an Exception 

## Feature
Throw an exception immediately when an error is being detected/reported via `ErrorHandling`.
For that create a new exception class, which takes in the `ErrorMessage` as it's constructor parameter (use the `errMsg` field as the value of `Exception.message`)

### PR DESCRIPTION
**Pull request by benedeki**
Closes #111

### CODE REVIEW

File: spark-commons/src/main/scala/za/co/absa/spark/commons/errorhandling/implementations/ErrorHandlerThrowingException.scala [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+   * @param dataFrame - the [[org.apache.spark.sql.DataFrame spark.DataFrame]] to apply the error columns to
+   * @param errCols   - the list of error columns to apply
+   * @return - data frame with the error columns applied (aggregated and attached or done otherwise)
+   */
+  override protected def doApplyErrorColumnsToDataFrame(dataFrame: DataFrame, errCols: Column*): DataFrame = {
+    import za.co.absa.spark.commons.implicits.StructTypeImplicits.StructTypeEnhancements
+    val errorColumn= coalesce(errCols: _*)
+    val errColName = dataFrame.schema.getClosestUniqueName("_1")
+    dataFrame.withColumn(errColName, when(errorColumn.isNull, null_col).otherwise(throwError(
+      //the values have to be sent decomposed, sending the whoel struct field fails the udf function
```
Comment (TebaleloS) [inline spark-commons/src/main/scala/za/co/absa/spark/commons/errorhandling/implementations/ErrorHandlerThrowingException.scala:48]: You have typo on line 48, word number 10. You wrote `whoel` instead of `whole`.

File: spark-commons/src/main/scala/za/co/absa/spark/commons/errorhandling/implementations/ErrorHandlerThrowingException.scala [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+   *
+   * @return - the DataType of the column containing the error info that is attached to the [[org.apache.spark.sql.DataFrame DataFrame]].
+   */
+  override def dataFrameColumnType: Option[DataType] = None
+
+  private val throwError = udf({
+    (errType: String, errCode: Long, errMsg: String, errColsAndValues: Map[String, String], additionInfo: String) => {
+      val error = ErrorMessage(errType, errCode, errMsg, errColsAndValues, Option(additionInfo))
+      throw ErrorHandlerException(error)
+
```
Comment (TebaleloS) [inline spark-commons/src/main/scala/za/co/absa/spark/commons/errorhandling/implementations/ErrorHandlerThrowingException.scala:69]: This line is unnecessary

File: spark-commons/src/main/scala/za/co/absa/spark/commons/errorhandling/implementations/ErrorHandlerThrowingException.scala [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+object ErrorHandlerThrowingException extends ErrorHandling with TransformIntoErrorMessage {
+  case class ErrorHandlerException(error: ErrorMessage) extends Exception(error.errMsg)
+
+  /**
+   * @see [[ErrorHandling.doApplyErrorColumnsToDataFrame]]
+   */
+  override protected def doApplyErrorColumnsToDataFrame(dataFrame: DataFrame, errCols: Column*): DataFrame = {
+    import za.co.absa.spark.commons.implicits.StructTypeImplicits.StructTypeEnhancements
+    val errorColumn= coalesce(errCols: _*)
+    val errColName = dataFrame.schema.getClosestUniqueName("_1")
```
Comment (lsulak) [inline spark-commons/src/main/scala/za/co/absa/spark/commons/errorhandling/implementations/ErrorHandlerThrowingException.scala:36]: so the column name will be `_1_1` - a bit odd although I know that it's temporary and will be almost immediately dropped. But if there is an error and we need to debug it, it can be better to have a bit more descriptive name still. But I'll leave it up to you

**Review by lsulak — COMMENTED** [review]
LGTM, found a tiny potential improvement.

- [x]  code reviewed
- [x]  pulled
- [x]  built
- [x]  ran tests

File: spark-commons/src/main/scala/za/co/absa/spark/commons/errorhandling/implementations/ErrorHandlerThrowingException.scala (hunk 3 above)
Comment (benedeki) [reply spark-commons/src/main/scala/za/co/absa/spark/commons/errorhandling/implementations/ErrorHandlerThrowingException.scala:36]: Odd is good. It avoids name clashes 😉 
What name would you suggest?

Comment (TebaleloS) [reply spark-commons/src/main/scala/za/co/absa/spark/commons/errorhandling/implementations/ErrorHandlerThrowingException.scala:36]: How about 1temporaryErrCol`?

Comment (benedeki) [reply spark-commons/src/main/scala/za/co/absa/spark/commons/errorhandling/implementations/ErrorHandlerThrowingException.scala:36]: OK, went with more more SQL standard and prefixing an underscore, which is a typical sign of "more private" field: `_temporary_err_col`.

**Review by TebaleloS — APPROVED** [review]

**Review by lsulak — APPROVED** [review]
