### PR TITLE
#80 Add enforceTypeOnNullTypeFields function to DataFrameImplicits

### LINKED ISSUE #80: Add function casting all NullType fields to a target type
## Background
In Spark, a field can have `NullType` type if it contains only nulls (untyped). It is problematic especially if one expects this field to be an array of something, and calls `transform` on it - in that case, an exception is thrown. 

## Feature
Function that would convert all fields with NullTypes to their corresponding type in target schema.

### PR DESCRIPTION
**Pull request by jakipatryk**
Closes #80

### CODE REVIEW

**Review by dk1844 — DISMISSED** [review]
Looks amazing (just read the code, but test seems to cover *a lot*)

**Comment by lsulak** [comment]
LGTM (just read the code)

File: spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala [hunk 1]
```diff
@@ -83,6 +85,68 @@ object DataFrameImplicits {
...
+      def processStruct(
+                         currentThisSchema: StructType, currentTargetSchema: StructType, parent: Option[Column]
+                       ): List[Column] = {
+        val currentTargetSchemaMap = currentTargetSchema.map(f => (f.name.toLowerCase, f)).toMap
+
+        currentThisSchema.foldRight(List.empty[Column])((field, acc) => {
+          val currentColumn: Column = parent
+            .map(_.getField(field.name))
+            .getOrElse(col(field.name))
+            .as(field.name)
```
Comment (benedeki) [inline spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala:130]: This can be omitted, if the `.as` is added to the `_` case bellow (as it's present in all other cases as well.

File: spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala [hunk 2]
```diff
@@ -83,6 +85,68 @@ object DataFrameImplicits {
...
+          val correspondingTargetType = currentTargetSchemaMap.get(field.name.toLowerCase).map(_.dataType)
+
+          (field.dataType, correspondingTargetType) match {
+            case (NullType, Some(targetType)) =>
```
Comment (benedeki) [inline spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala:134]: As above would add 
```suggestion
          (field.dataType, correspondingTargetType) match {
            case (NullType, Some(NullType) => currentColumn.as(field.name) :: acc
            case (NullType, Some(targetType)) =>
```

File: spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala [hunk 3]
```diff
@@ -83,6 +85,68 @@ object DataFrameImplicits {
...
+              currentColumn.cast(targetType).as(field.name) :: acc
+            case (arrType: ArrayType, Some(targetArrType: ArrayType)) =>
+              processArray(arrType, targetArrType, currentColumn).as(field.name) :: acc
+            case (structType: StructType, Some(targetStructType: StructType)) =>
+              struct(processStruct(structType, targetStructType, Some(currentColumn)): _*).as(field.name) :: acc
+            case _ => currentColumn :: acc
```
Comment (benedeki) [inline spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala:140]: **Possibly major:**
This will result the output of the function will contain even fields that are not present in the target schema. I think that is not desired by the expected logic of the function. 🤔

**Review by benedeki — COMMENTED** [review]
I actually wonder about the universality of the function. 🤔 
Why are `NullType` so special, that they have to be cast but other misaligned types are kept as they were?

File: spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala [hunk 4]
```diff
@@ -83,6 +85,68 @@ object DataFrameImplicits {
...
+     * @param targetSchema definition of field types to which potential NullTypes will be casted to
+     * @return DataFrame with fields of NullType casted to their type in `targetSchema`
+     */
+    def enforceTypeOnNullTypeFields(targetSchema: StructType): DataFrame = {
+
+      def processArray(
+                        thisArrType: ArrayType, targetArrType: ArrayType, thisArrayColumn: Column
+                      ): Column =
+        (thisArrType.elementType, targetArrType.elementType) match {
+          case (_: NullType, _) =>
```
[the remark this answers is not in the document]
Comment (jakipatryk) [reply spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala:105]: Good point. Done.

File: spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala [hunk 5]
```diff
@@ -83,6 +85,68 @@ object DataFrameImplicits {
...
+              thisArrayColumn,
+              element => struct(processStruct(thisNestedStructType, targetNestedStructType, Some(element)): _*)
+            )
+          case _ => thisArrayColumn
+        }
+
+      def processStruct(
+                         currentThisSchema: StructType, currentTargetSchema: StructType, parent: Option[Column]
+                       ): List[Column] = {
+        val currentTargetSchemaMap = currentTargetSchema.map(f => (f.name.toLowerCase, f)).toMap
```
[the remark this answers is not in the document]
Comment (jakipatryk) [reply spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala:126]: I would keep it as it is, its `currentTargetSchemaMap` and next there is `correspondingTargetType` reused in all other places. Having two separate vals makes them a bit easier to understand IMO.

File: spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala (hunk 1 above)
Comment (jakipatryk) [reply spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala]: Yup, changed.

File: spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala (hunk 2 above)
Comment (jakipatryk) [reply spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala]: Not as important as one above (basically no performance impact here), but changed as well.

File: spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala (hunk 3 above)
Comment (jakipatryk) [reply spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala]: IMO it is desired - all the function does is enforcing types on NullType, ofc in case if field is present in `targetSchema` (otherwise it cannot enforce anything). Added a line in docstring saying what is the desired behaviour.

File: spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala (hunk 5 above)
[the remark this answers is not in the document]
Comment (benedeki) [reply spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala:126]: I didn't say to get rid of the two `val`s. 😉 . What I meant, that the map now named `currentTargetSchemaMap ` could be not a map of `StructField`s, but just `DataType`s. Would make it smaller and easier to read. And it's not used elsewhere...
`correspondingTargetType` would stay...
But it's not a biggie, can stay like you have it.

File: spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala (hunk 3 above)
Comment (benedeki) [reply spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala]: OK, that makes sense, and the added _docstring_ helps considerably in this regard. 😎 

In that case I would suggest, to avoid code repetition, to assign the result of the match-case statement to a `val` of type column, eg. `val castedColumn`. And only then construct the result:
`castedColumn.as(field.name) :: acc`

**Comment by benedeki** [comment]
> > I actually wonder about the universality of the function. 🤔
> > Why are NullType so special, that they have to be cast but other misaligned types are kept as they were?
> 
>     1. NullType can be casted to any type, so the function is expected to not fail in any case.
> 
>     2. NullType isn't cool, because it doesn't work when `transform` is called on it, and it breaks for example `alignSchema` :D

Agreed offline to keep the function in the library. 👍

File: spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala (hunk 3 above)
Comment (jakipatryk) [reply spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala]: Good idea again, done

File: spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala (hunk 5 above)
[the remark this answers is not in the document]
Comment (jakipatryk) [reply spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala:126]: Yeah I understand. If it is ok I would leave it as it as, though your version is ok to me too and I can commit a change, just I prefer a little bit the one that's in the code now.

[the remark this answers is not in the document]
Comment (benedeki) [reply spark-commons/src/main/scala/za/co/absa/spark/commons/implicits/DataFrameImplicits.scala:126]: Sure, no problem. 👍

**Review by benedeki — APPROVED** [review]
Nicely done, thank you 🙇
